---
title: "Починали ваксинирани"
---
    
   
```{r, include=FALSE}
library("tidyverse")
library("readr")
library("ggplot2")
library(httr)
library(jsonlite)

body <- list("resource_uri" = "e6a72183-28e0-486a-b4e4-b5db8b60a900")
r <- POST("https://data.egov.bg/api/getResourceData", body = body, encode = "json")
r1 <- fromJSON(rawToChar(r$content))

x <- as.data.frame(r1[[2]])

x = x[-1,]
x[[1]]<-as.Date(x[[1]],"%Y/%m/%d")
x[[5]]<-as.numeric(x[[5]])
date <- x[[1]]
numberOfInfected <- x[[5]]
```
```{r,echo=FALSE}
ggplot(data = x, aes(x = date, y = numberOfInfected)) + 
  geom_bar(stat = "identity",fill="DarkGreen") +
  labs(title = "Number of deaths per day.",
           substitute = "2021",
           x = "Date", y = "Number of deaths")

```

```{r,echo=FALSE}
x <- filter(x,!V2=="-")
vaccine <- x[[2]]
numberOfInfected <- x[[1]]
ggplot(data = x, aes(x = vaccine, y = numberOfInfected)) + 
  geom_bar(stat = "identity",fill="orange") +
  coord_flip()+
  labs(title = "Number of deaths by the type of vaccine.",
           substitute = "2021",
           x = "Type of vaccine", y = "Number of deaths")+
   scale_y_continuous(expand = expansion(mult = c(0, 0.05)),labels = scales::label_number(scale = 1/10000))
```

```{r,echo=FALSE}
ageGroup <- x[[4]]
numberOfInfected <- x[[1]]
ggplot(data = x, aes(x = ageGroup, y = numberOfInfected)) + 
  geom_bar(stat = "identity",fill="red") +
  labs(title = "Number of deaths by age",
           substitute = "2021",
           x = "Age", y = "Number of deaths")+
   scale_y_continuous(expand = expansion(mult = c(0, 0.05)),labels = scales::label_number(scale = 1/10000))
```
